# Generated by Django 2.2.3 on 2019-07-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=30)),
                ('car_model', models.CharField(max_length=30)),
                ('car_year', models.DateField()),
            ],
        ),
    ]
