# Generated by Django 2.2.3 on 2019-07-19 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_report', '0002_auto_20190719_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoparts',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_report.Car', verbose_name='Модель автомобиля'),
        ),
        migrations.AlterField(
            model_name='autoparts',
            name='part_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_report.AutoPartsType', verbose_name='Тип автозапчасти'),
        ),
        migrations.AlterField(
            model_name='autoparts',
            name='parts_name',
            field=models.CharField(max_length=200, verbose_name='Название автозапчасти'),
        ),
        migrations.AlterField(
            model_name='autopartstype',
            name='parts_type',
            field=models.CharField(max_length=200, verbose_name='Тип автозапчасти'),
        ),
        migrations.AlterField(
            model_name='autopartswarehouse',
            name='numbers_of_pats',
            field=models.PositiveIntegerField(verbose_name='Количество запчастей'),
        ),
        migrations.AlterField(
            model_name='autopartswarehouse',
            name='parts_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stock_report.AutoParts', verbose_name='Название автозапчасти'),
        ),
        migrations.AlterField(
            model_name='autopartswarehouse',
            name='price_of_parts',
            field=models.PositiveIntegerField(verbose_name='Цена 1й запчати'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_brand',
            field=models.CharField(max_length=200, verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(max_length=200, verbose_name='Модель автомобиля'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_year',
            field=models.DateField(verbose_name='Год выпуска'),
        ),
    ]
