# Generated by Django 2.2.3 on 2019-08-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoparts',
            old_name='part_type',
            new_name='parts_type',
        ),
    ]
