# Generated by Django 2.2.3 on 2019-08-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0002_auto_20190810_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autopartswarehouse',
            old_name='parts_name',
            new_name='parts_name_warehouse',
        ),
    ]
