# Generated by Django 2.2.3 on 2019-08-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0003_auto_20190812_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoparts',
            name='id',
        ),
        migrations.AlterField(
            model_name='autoparts',
            name='parts_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Название автозапчасти'),
        ),
    ]
