# Generated by Django 2.2.3 on 2019-08-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0004_auto_20190812_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoparts',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autoparts',
            name='parts_name',
            field=models.CharField(max_length=200, verbose_name='Название автозапчасти'),
        ),
    ]
